kind: ENC[AES256_GCM,data:TSOfbon4,iv:l25FydYeZkoWzH0cGw+xaZOWiCtPJGZ0CLnwyEzsB8A=,tag:DC19ToeMZ3HdGhOYYW1Vdw==,type:str]
ansible_user: ENC[AES256_GCM,data:Ut9wTdz7hQ==,iv:ySIcHvd8PW4++/oeMvSlOsGhYwW8j8LbMgwinsJZeOQ=,tag:kJdSSendzmuw070h5F4jCQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:22999byL+ojA,iv:4BuQoWnvdWFUgseZL7YetIuL0woBNPjnsNzb0RvbWPg=,tag:wvqOQsjEntRsjjR6tb5DYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTEttQytXQWpyODNlenND
            bXpweGh2U0QxRVZVeTc4OVNmcmhsNlZZLzE0ClY1aWNwSGZGeWxRWnAvZDYyY2lF
            a1JiWXBkdUV3YnpuOVpaYitKVk9GZGcKLS0tIHJaRlp5N0l3Yy94TmxLSDRtM0Iv
            TW1XNmsyYitGUkZJNXVpam5ITGZJMVEKB7d/8B4gLP2vot3mQ/+GZoGnjdkRpRwV
            gmrOSoIeEMAOBe6LwOXjy6Sd8p5qGwZ+sXcx2xbXpEfr0s2e99CtVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T15:24:11Z"
    mac: ENC[AES256_GCM,data:s6+ASiQMxRqz9edywLG5gjPwxntA1yG3MLsKnHQ5EByoh2d2jtRW6JftpVJ84Esm6PO5oL/MqSosN9/XDUVf23kClbqoK0kgJjB1/R5rE5PrthARHVnzVsZh9s9JGd+Rrd5U5yaBsVRIz/vH8zAP86mIGHxQhfz0mi4SqRptrXM=,iv:QXvgUKqLDTGwuDxnhbeORksEec+yuVYCiAHDWec4MEo=,tag:SpaKwSCgWZeBEh4oXEoJ2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
