---
kubernetes:
  children:
    master:
      hosts:
        k3s-nvme1:
          ansible_host: 192.168.10.94
        k3s-nvme2:
          ansible_host: 192.168.10.95
        k3s-nvme3:
          ansible_host: 192.168.10.96
    worker:
      hosts:
        k3s-nvme4:
          ansible_host: 192.168.10.97
        k3s-nvme5:
          ansible_host: 192.168.10.98
        k3s-nvme6:
          ansible_host: 192.168.10.99
