apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:N0Ph2LdXcNEJXV2EtCINiJmP3Io4,iv:wT/UKNE3ZDu5EFGFF6+FSnUtJJ7tGB543SmZTme5Ehg=,tag:uA3Qhz8uy2xnekxfbNYyaQ==,type:str]
    api-key: ENC[AES256_GCM,data:ZNy9ZheynKFr6iz601p72Ldx50H57QkSQm8ex/jb7Nbhvc2KRg==,iv:6VDa84eBo1rif48eeivSLZYFlla8pkNzXt4Ih7TnHFQ=,tag:ZIcJxuIY3dya/dl+/Gh7VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydmNoa1pQMHQ1cW5Oa3RX
            UFlubXBZSlY4NG0wTXNWR051UG0zTW9lNUNvCkhmNXhjeW9rUzBYdlRJaWkwdm42
            eDRTREZqd1hlc2lZZVJIaDF0RWZDYlUKLS0tIDkvQ0ZBb3hBZUhXN01CZXYrKzBD
            WE9SWG1hVzM5SmwzamhuNTFpd1A0cDQK02saoJjuPk+iKfG5PCgp4NpNsFI5eXjD
            yg8ADPa8EOJVNpP0S2Ptm1twncnrR2QTpAOBIa991N6AMOt6rZEq0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T20:33:34Z"
    mac: ENC[AES256_GCM,data:NUtor+En7CFDjmsWRFHdzguwHmgdBRNV7cx/dn0cBkpChvJkSkEPpYS/jmMysPRKoHGCMPAdOTg4VKvJf2gFbctY/naoFbJ4f4nNNWt/Lnb7FdDFrbtznOSadIctaSEipVGpax2R/5egfotUA9thb6TwwJ9k8vHo/+PZGZhuM6w=,iv:rgfb5aiMK7NUG/ghHoubdNdQiVv0s9K2wG2IumzNezQ=,tag:4PyUj3NqntYIBq8bEfKyLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
