apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:5uIapaLjIouZw9xiGdjLRkFGUXT9,iv:dZvT1XbXacS5Ph7gJySBe/Tv3cYBq01GsSwq0E6cuwI=,tag:1eH9QBDT2iZrOyTmYImCTQ==,type:str]
    api-key: ENC[AES256_GCM,data:jB1uYB47E5ZPxX910uHvzs2gFFxNhR2cDy/ZlwN1QiyKLOjRJQ==,iv:UhpxtDiEra+KfnLO11Ihm5Vrb7CR5XhmclXsphiDnVE=,tag:CgUysmvmsbm/vyRHOPniIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWJvcHEzTlFmbW1KMEt3
            aFJRMDAxZjM2ZHNMcjZ6d2JoUlpnT2pXQUIwClI4NldFMVZXRE1nQnRxOTlXZU5P
            REFEc1Z2cC8zMytBcHowaDlnNUdWUzAKLS0tIGJoNTNHdzRRcGVDSUl0WGdEZVdk
            L2hnbkRFWFNDVTFrMUl5Y1dOKzRFQ2sK/4tyRpgQtc2meAx2yzxtlm4xW2rRafla
            fc8HPEz2wTxBhGBumRJSo8PhwtOM8VL2BlHTGZS2hGhuIpVyTu4GPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T15:24:11Z"
    mac: ENC[AES256_GCM,data:ld/Sbs/HLI+KQCH1+WroCIzt4ErTAKRVULJzEvkLSuMcsBAEgyY/VxY/sgM4Sygk0QmN13RG1mBNSiWBmJsLM3o91RvxmW2mS/N/eaCP77gVseEP2berXG4Q531I2WCHH8TYodE61KFV/dC93ykNUedc/Ni1g1Uomgu6obGIqVA=,iv:zFVUEac9jFkGSt3OsPVNmofb0y8vtLcPXb10Z49OhoY=,tag:hhiJZzpGBTENXktVPvQDhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
