apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:QOwnEM4=,iv:ky9fjDJK1Dt3n3D+f7cT3gXzZHpbhqSgGbB1P2eAYhA=,tag:V/aRBETc9rQw+5E5GULEQg==,type:str]
    password: ENC[AES256_GCM,data:uP7upOCQns90ex54q79liY3klMHJo/zJr/B2cN5S9tX/6b3b0HajoUHlXUIWppSfQLiL8l8COrc6gPtQ,iv:mRXGf8bNafgrm1uFk9SrMWl1UKhN/BFnISpzdDxpe3w=,tag:nDOKCIPDblWmIEpScEL/eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdjlscm9jenJwdHBjR1VW
            eGhuS2t1TVhOeE1wdUpUUGJvcDk3RTRlanhFCjJ3R3ZuYUV6M21pdmhLeENxK3NL
            M3J5cy9mVG1NbjUrc2ZlRnlZRzQ5THcKLS0tIHo1OHJwS3h3N0x1YWtqaVBUa1Np
            Z2owVEdHVXVabEFhUm9pdTBnSllCL1UKaFTA3FjziZDwQLNrwomhA2LuWFQ1Iuhn
            Lp/Q4YXwRWwD/bzefco4h5T0gwCBFtAS/avD7m0BEl0v7z4PqErQ8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T15:24:12Z"
    mac: ENC[AES256_GCM,data:LjiFOt/KJjg68YydX/PumxiM5dpLrxyRhw7lYXazFXWCI8j/91Ud6fS/owvaGrXIH6OzP/7FY+Wd3gJ/vCI4ny7R2rki9CGjPBK9d6Cw/ORsPQ23F8ZS5JTzc1N6u93rkNOOOaKdTlaYEj961FzB32MexSMjGQrGZnYRi9R2Fro=,iv:zqi1+EsFlSz/cOX/1juql/vGTBO9JsNF3MitYjJmLZE=,tag:zAn/RecHxOuN9WtDhmd42Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
